-- SQL Script to Fix Admin User Password
-- This script updates the existing admin user with a proper bcrypt hash
--
-- IMPORTANT: Replace the password_hash below with the hash generated by:
--   node generate-password-hash.js "yourpassword"
--
-- For the password "asdf." the hash would be generated like:
--   node generate-password-hash.js "asdf."

-- Example: Update existing admin user with proper bcrypt hash
-- First, generate the hash using the Node.js script, then replace the hash below

UPDATE platform_users 
SET 
  password_hash = '$2b$10$RbAncaBOrJl7xKF4qBdgSORfFeUZc6qqvmeIsM.Q2Wg9JweHOUb1u',  -- Hash for "asdf."
  status = 'active',
  role = 'PLATFORM_ADMIN',
  updated_at = NOW()
WHERE username = 'admin';

-- Verify the update
SELECT 
  id,
  username,
  email,
  role,
  status,
  LENGTH(password_hash) as password_hash_length,
  LEFT(password_hash, 10) as password_hash_prefix,
  created_at,
  updated_at
FROM platform_users
WHERE username = 'admin';

-- Expected output:
-- - password_hash_length should be 60
-- - password_hash_prefix should start with $2b$10$
-- - role should be PLATFORM_ADMIN
-- - status should be active
