-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.accounting_periods
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    period_type text COLLATE pg_catalog."default" NOT NULL,
    period_start timestamp with time zone NOT NULL,
    period_end timestamp with time zone NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'OPEN'::text,
    closed_by character varying(100) COLLATE pg_catalog."default",
    closed_at timestamp with time zone,
    closure_notes text COLLATE pg_catalog."default",
    created_by character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT accounting_periods_pkey PRIMARY KEY (id),
    CONSTRAINT uq_acct_period_tenant_type_dates UNIQUE (tenant_id, period_type, period_start, period_end)
);

CREATE TABLE IF NOT EXISTS public.admin_overrides_log
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    override_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    justification text COLLATE pg_catalog."default" NOT NULL,
    entity_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    entity_id uuid,
    affected_entities jsonb,
    override_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    override_by_role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    override_by_email character varying(255) COLLATE pg_catalog."default",
    approved_by character varying(100) COLLATE pg_catalog."default",
    approved_at timestamp with time zone,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent character varying(500) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    metadata jsonb,
    approval_reason text COLLATE pg_catalog."default",
    approved_by_role character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT admin_overrides_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.approval_requests
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    request_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    requestor_id uuid NOT NULL,
    approver_id uuid,
    status text COLLATE pg_catalog."default" DEFAULT 'pending'::text,
    request_data jsonb NOT NULL,
    approval_reason text COLLATE pg_catalog."default",
    requested_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    approved_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT approval_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    entity_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    entity_id uuid NOT NULL,
    action text COLLATE pg_catalog."default" NOT NULL,
    user_id character varying(100) COLLATE pg_catalog."default",
    user_email character varying(255) COLLATE pg_catalog."default",
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent character varying(500) COLLATE pg_catalog."default",
    changes_before jsonb,
    changes_after jsonb,
    metadata jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    action_category character varying(100) COLLATE pg_catalog."default",
    action_type character varying(100) COLLATE pg_catalog."default",
    resource_type character varying(100) COLLATE pg_catalog."default",
    resource_id uuid,
    user_role character varying(50) COLLATE pg_catalog."default",
    details jsonb,
    correlation_id uuid,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.audit_portal_access_log
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    auditor_user_id uuid NOT NULL,
    endpoint character varying(255) COLLATE pg_catalog."default" NOT NULL,
    http_method character varying(10) COLLATE pg_catalog."default" NOT NULL,
    http_status_code integer,
    ip_address character varying(50) COLLATE pg_catalog."default",
    user_agent character varying(500) COLLATE pg_catalog."default",
    query_parameters jsonb,
    access_purpose text COLLATE pg_catalog."default",
    response_time_ms integer,
    records_returned integer,
    accessed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT audit_portal_access_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.audit_trail
(
    id serial NOT NULL,
    event_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    event_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    user_id character varying(100) COLLATE pg_catalog."default",
    action character varying(50) COLLATE pg_catalog."default",
    resource character varying(100) COLLATE pg_catalog."default",
    resource_id character varying(100) COLLATE pg_catalog."default",
    data_type character varying(50) COLLATE pg_catalog."default",
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    success boolean DEFAULT true,
    reason text COLLATE pg_catalog."default",
    metadata jsonb,
    "timestamp" timestamp with time zone NOT NULL,
    hash character varying(64) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT audit_trail_pkey PRIMARY KEY (id),
    CONSTRAINT audit_trail_event_id_unique UNIQUE (event_id)
);

CREATE TABLE IF NOT EXISTS public.auditor_access_windows
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    auditor_user_id uuid NOT NULL,
    access_start_date timestamp with time zone NOT NULL,
    access_end_date timestamp with time zone NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'ACTIVE'::text,
    audit_case_number character varying(100) COLLATE pg_catalog."default",
    audit_type character varying(100) COLLATE pg_catalog."default",
    audit_purpose text COLLATE pg_catalog."default",
    granted_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    granted_by_role character varying(50) COLLATE pg_catalog."default",
    revocation_reason text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_access_at timestamp with time zone,
    revoked_at timestamp with time zone,
    CONSTRAINT auditor_access_windows_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bank_statement_batches
(
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    bank_account_id uuid,
    source_type text COLLATE pg_catalog."default" NOT NULL,
    source_filename character varying(255) COLLATE pg_catalog."default",
    source_reference character varying(255) COLLATE pg_catalog."default",
    imported_by character varying(100) COLLATE pg_catalog."default",
    import_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::text,
    total_lines integer NOT NULL DEFAULT 0,
    imported_lines integer NOT NULL DEFAULT 0,
    duplicate_lines integer NOT NULL DEFAULT 0,
    failed_lines integer NOT NULL DEFAULT 0,
    error_message text COLLATE pg_catalog."default",
    imported_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    correlation_id uuid,
    CONSTRAINT bank_statement_batches_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bank_statement_lines
(
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    batch_id uuid NOT NULL,
    bank_account_id uuid,
    transaction_date date NOT NULL,
    value_date date,
    bank_transaction_id character varying(100) COLLATE pg_catalog."default",
    utr_number character varying(100) COLLATE pg_catalog."default",
    bank_reference_number character varying(100) COLLATE pg_catalog."default",
    external_reference character varying(255) COLLATE pg_catalog."default",
    narration text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    debit_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    credit_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    amount numeric(15, 2) NOT NULL,
    currency character varying(3) COLLATE pg_catalog."default" NOT NULL DEFAULT 'INR'::character varying,
    transaction_type text COLLATE pg_catalog."default" NOT NULL,
    counterparty_name character varying(255) COLLATE pg_catalog."default",
    counterparty_account character varying(100) COLLATE pg_catalog."default",
    raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    normalized_hash character varying(128) COLLATE pg_catalog."default" NOT NULL,
    reconciliation_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'UNMATCHED'::text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    correlation_id uuid,
    CONSTRAINT bank_statement_lines_pkey PRIMARY KEY (id),
    CONSTRAINT uq_bank_stmt_lines_tenant_hash UNIQUE (tenant_id, normalized_hash)
);

CREATE TABLE IF NOT EXISTS public.beneficiaries
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    beneficiary_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    account_number character varying(100) COLLATE pg_catalog."default" NOT NULL,
    ifsc_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    bank_name character varying(255) COLLATE pg_catalog."default",
    branch_name character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default" DEFAULT 'active'::text,
    metadata jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT beneficiaries_pkey PRIMARY KEY (id),
    CONSTRAINT beneficiaries_tenant_id_account_number_ifsc_code_unique UNIQUE (tenant_id, account_number, ifsc_code)
);

CREATE TABLE IF NOT EXISTS public.circuit_breakers
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    gateway character varying(50) COLLATE pg_catalog."default" NOT NULL,
    state text COLLATE pg_catalog."default" NOT NULL DEFAULT 'closed'::text,
    failure_count integer DEFAULT 0,
    success_count integer DEFAULT 0,
    last_failure_time timestamp with time zone,
    last_success_time timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT circuit_breakers_pkey PRIMARY KEY (id),
    CONSTRAINT circuit_breakers_gateway_unique UNIQUE (gateway)
);

CREATE TABLE IF NOT EXISTS public.compliance_reports_cache
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    report_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    report_date timestamp with time zone NOT NULL,
    period_start timestamp with time zone,
    period_end timestamp with time zone,
    report_data jsonb NOT NULL,
    report_metadata jsonb,
    generated_by character varying(100) COLLATE pg_catalog."default",
    generated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    generation_duration_ms integer,
    expires_at timestamp with time zone,
    is_final boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT compliance_reports_cache_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.config_history
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    config_id uuid NOT NULL,
    config_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    old_value jsonb,
    new_value jsonb,
    changed_by uuid NOT NULL,
    change_reason text COLLATE pg_catalog."default",
    changed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT config_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.data_retention_tracking
(
    id serial NOT NULL,
    data_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    data_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    table_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    scheduled_deletion_at timestamp with time zone,
    retention_days integer NOT NULL,
    deleted boolean DEFAULT false,
    deleted_at timestamp with time zone,
    deletion_method character varying(50) COLLATE pg_catalog."default",
    deleted_by character varying(100) COLLATE pg_catalog."default",
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT data_retention_tracking_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.disputes
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    merchant_id uuid NOT NULL,
    transaction_id uuid NOT NULL,
    dispute_ref character varying(100) COLLATE pg_catalog."default" NOT NULL,
    disputed_amount numeric(15, 2) NOT NULL,
    currency character varying(3) COLLATE pg_catalog."default" DEFAULT 'INR'::character varying,
    dispute_type text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'open'::text,
    reason_code character varying(50) COLLATE pg_catalog."default",
    customer_reason text COLLATE pg_catalog."default",
    merchant_response text COLLATE pg_catalog."default",
    gateway_dispute_id character varying(255) COLLATE pg_catalog."default",
    dispute_date date NOT NULL,
    response_due_date date,
    resolved_date date,
    evidence jsonb,
    metadata jsonb,
    raised_by character varying(255) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT disputes_pkey PRIMARY KEY (id),
    CONSTRAINT disputes_dispute_ref_unique UNIQUE (dispute_ref)
);

CREATE TABLE IF NOT EXISTS public.gateway_settlement_batches
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    gateway_name character varying(80) COLLATE pg_catalog."default" NOT NULL,
    gateway_settlement_id character varying(255) COLLATE pg_catalog."default",
    settlement_cycle_start timestamp with time zone,
    settlement_cycle_end timestamp with time zone,
    expected_settlement_date date,
    actual_settlement_date date,
    settlement_utr character varying(255) COLLATE pg_catalog."default",
    bank_reference_number character varying(255) COLLATE pg_catalog."default",
    source_type text COLLATE pg_catalog."default" NOT NULL,
    source_filename character varying(500) COLLATE pg_catalog."default",
    source_reference character varying(500) COLLATE pg_catalog."default",
    import_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::text,
    total_lines integer NOT NULL DEFAULT 0,
    imported_lines integer NOT NULL DEFAULT 0,
    duplicate_lines integer NOT NULL DEFAULT 0,
    failed_lines integer NOT NULL DEFAULT 0,
    gross_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    total_gateway_fee numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    total_gst_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    total_adjustment_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    net_settlement_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    currency character varying(3) COLLATE pg_catalog."default" NOT NULL DEFAULT 'INR'::character varying,
    raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    error_message text COLLATE pg_catalog."default",
    imported_by character varying(100) COLLATE pg_catalog."default",
    imported_at timestamp with time zone,
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT gateway_settlement_batches_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.gateway_settlement_lines
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    batch_id uuid NOT NULL,
    gateway_name character varying(80) COLLATE pg_catalog."default" NOT NULL,
    gateway_settlement_id character varying(255) COLLATE pg_catalog."default",
    gateway_settlement_line_id character varying(255) COLLATE pg_catalog."default",
    transaction_id uuid,
    transaction_ref character varying(100) COLLATE pg_catalog."default",
    gateway_transaction_id character varying(255) COLLATE pg_catalog."default",
    gateway_payment_id character varying(255) COLLATE pg_catalog."default",
    order_id character varying(100) COLLATE pg_catalog."default",
    merchant_id uuid,
    line_type text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PAYMENT'::text,
    gateway_status character varying(100) COLLATE pg_catalog."default",
    transaction_date timestamp with time zone,
    captured_at timestamp with time zone,
    settled_at timestamp with time zone,
    gross_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    gateway_fee numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    gst_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    adjustment_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    net_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    currency character varying(3) COLLATE pg_catalog."default" NOT NULL DEFAULT 'INR'::character varying,
    expected_gateway_fee numeric(15, 2),
    expected_gst_amount numeric(15, 2),
    expected_net_amount numeric(15, 2),
    fee_discrepancy_amount numeric(15, 2),
    gst_discrepancy_amount numeric(15, 2),
    net_discrepancy_amount numeric(15, 2),
    pricing_rule_id uuid,
    pricing_snapshot jsonb,
    raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    normalized_hash character varying(128) COLLATE pg_catalog."default" NOT NULL,
    reconciliation_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'UNMATCHED'::text,
    ledger_transaction_id uuid,
    outbox_event_id uuid,
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT gateway_settlement_lines_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.gateway_settlement_signals
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    signal_type text COLLATE pg_catalog."default" NOT NULL,
    severity text COLLATE pg_catalog."default" NOT NULL,
    signal_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'OPEN'::text,
    source_type text COLLATE pg_catalog."default" NOT NULL,
    source_id uuid,
    batch_id uuid,
    line_id uuid,
    transaction_id uuid,
    transaction_ref character varying(100) COLLATE pg_catalog."default",
    gateway_name character varying(80) COLLATE pg_catalog."default" NOT NULL,
    gateway_settlement_id character varying(255) COLLATE pg_catalog."default",
    gateway_transaction_id character varying(255) COLLATE pg_catalog."default",
    impact_amount numeric(15, 2),
    currency character varying(3) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default" NOT NULL,
    suggested_action text COLLATE pg_catalog."default",
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT gateway_settlement_signals_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.gateway_webhook_events
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    gateway_name character varying(80) COLLATE pg_catalog."default" NOT NULL,
    gateway_event_id character varying(255) COLLATE pg_catalog."default",
    gateway_event_type character varying(150) COLLATE pg_catalog."default" NOT NULL,
    gateway_payment_id character varying(255) COLLATE pg_catalog."default",
    gateway_order_id character varying(255) COLLATE pg_catalog."default",
    transaction_ref character varying(100) COLLATE pg_catalog."default",
    order_id character varying(100) COLLATE pg_catalog."default",
    raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    raw_headers jsonb NOT NULL DEFAULT '{}'::jsonb,
    payload_hash character varying(128) COLLATE pg_catalog."default" NOT NULL,
    signature_header character varying(500) COLLATE pg_catalog."default",
    signature_verified boolean NOT NULL DEFAULT false,
    verification_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::text,
    event_created_at timestamp with time zone,
    received_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at timestamp with time zone,
    processing_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'RECEIVED'::text,
    failure_reason text COLLATE pg_catalog."default",
    retry_count integer NOT NULL DEFAULT 0,
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT gateway_webhook_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.idempotency_keys
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    scope character varying(100) COLLATE pg_catalog."default" NOT NULL,
    idempotency_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    request_hash character varying(128) COLLATE pg_catalog."default" NOT NULL,
    response_body jsonb,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'IN_PROGRESS'::text,
    error_message text COLLATE pg_catalog."default",
    locked_until timestamp with time zone,
    expires_at timestamp with time zone,
    correlation_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT idempotency_keys_pkey PRIMARY KEY (id),
    CONSTRAINT uq_idempotency_tenant_scope_key UNIQUE (tenant_id, scope, idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.knex_migrations
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    batch integer,
    migration_time timestamp with time zone,
    CONSTRAINT knex_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.knex_migrations_lock
(
    index serial NOT NULL,
    is_locked integer,
    CONSTRAINT knex_migrations_lock_pkey PRIMARY KEY (index)
);

CREATE TABLE IF NOT EXISTS public.ledger_accounts
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    account_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    account_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    account_type text COLLATE pg_catalog."default" NOT NULL,
    normal_balance text COLLATE pg_catalog."default" NOT NULL,
    category text COLLATE pg_catalog."default" NOT NULL,
    merchant_id uuid,
    gateway_name character varying(50) COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default" DEFAULT 'active'::text,
    metadata jsonb,
    created_by character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    tenant_id uuid,
    CONSTRAINT ledger_accounts_pkey PRIMARY KEY (id),
    CONSTRAINT ledger_accounts_account_code_unique UNIQUE (account_code)
);

CREATE TABLE IF NOT EXISTS public.ledger_audit_logs
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    entity_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    entity_id uuid NOT NULL,
    action text COLLATE pg_catalog."default" NOT NULL,
    user_id character varying(100) COLLATE pg_catalog."default",
    user_email character varying(255) COLLATE pg_catalog."default",
    user_role character varying(50) COLLATE pg_catalog."default",
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent character varying(500) COLLATE pg_catalog."default",
    source_system character varying(100) COLLATE pg_catalog."default",
    before_state jsonb,
    after_state jsonb,
    reason text COLLATE pg_catalog."default",
    metadata jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    correlation_id uuid,
    CONSTRAINT ledger_audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ledger_entries
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    transaction_id uuid NOT NULL,
    account_id uuid NOT NULL,
    entry_type text COLLATE pg_catalog."default" NOT NULL,
    amount numeric(15, 2) NOT NULL,
    currency character varying(3) COLLATE pg_catalog."default" DEFAULT 'INR'::character varying,
    description text COLLATE pg_catalog."default",
    metadata jsonb,
    created_by character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    correlation_id uuid,
    CONSTRAINT ledger_entries_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ledger_locks
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    lock_type text COLLATE pg_catalog."default" NOT NULL,
    lock_start_date timestamp with time zone NOT NULL,
    lock_end_date timestamp with time zone NOT NULL,
    accounting_period_id uuid,
    lock_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'ACTIVE'::text,
    reason text COLLATE pg_catalog."default" NOT NULL,
    reference_number character varying(100) COLLATE pg_catalog."default",
    locked_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    locked_by_role character varying(50) COLLATE pg_catalog."default",
    locked_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    released_by character varying(100) COLLATE pg_catalog."default",
    released_by_role character varying(50) COLLATE pg_catalog."default",
    released_at timestamp with time zone,
    release_notes text COLLATE pg_catalog."default",
    metadata jsonb,
    CONSTRAINT ledger_locks_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ledger_transactions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    transaction_ref character varying(100) COLLATE pg_catalog."default" NOT NULL,
    idempotency_key character varying(255) COLLATE pg_catalog."default",
    event_type text COLLATE pg_catalog."default" NOT NULL,
    source_transaction_id uuid,
    source_order_id character varying(100) COLLATE pg_catalog."default",
    amount numeric(15, 2) NOT NULL,
    currency character varying(3) COLLATE pg_catalog."default" DEFAULT 'INR'::character varying,
    description text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default" DEFAULT 'pending'::text,
    reverses_transaction_id uuid,
    reversed_by_transaction_id uuid,
    metadata jsonb,
    created_by character varying(100) COLLATE pg_catalog."default",
    source_event character varying(255) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    correlation_id uuid,
    CONSTRAINT ledger_transactions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.merchant_api_keys
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    merchant_id uuid NOT NULL,
    key_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    api_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    api_secret_encrypted text COLLATE pg_catalog."default" NOT NULL,
    api_secret_iv text COLLATE pg_catalog."default" NOT NULL,
    api_secret_auth_tag text COLLATE pg_catalog."default" NOT NULL,
    api_secret_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" DEFAULT 'active'::text,
    last_used_ip character varying(45) COLLATE pg_catalog."default",
    last_used_at timestamp with time zone,
    expires_at timestamp with time zone,
    permissions jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT merchant_api_keys_pkey PRIMARY KEY (id),
    CONSTRAINT merchant_api_keys_api_key_unique UNIQUE (api_key)
);

CREATE TABLE IF NOT EXISTS public.merchant_ip_whitelist
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    merchant_id uuid NOT NULL,
    ip_address character varying(45) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default" DEFAULT 'active'::text,
    last_used_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT merchant_ip_whitelist_pkey PRIMARY KEY (id),
    CONSTRAINT merchant_ip_whitelist_merchant_id_ip_address_unique UNIQUE (merchant_id, ip_address)
);

CREATE TABLE IF NOT EXISTS public.merchant_rate_limits
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    merchant_id uuid NOT NULL,
    endpoint_pattern character varying(255) COLLATE pg_catalog."default" NOT NULL,
    max_requests integer NOT NULL,
    window_ms integer NOT NULL,
    status text COLLATE pg_catalog."default" DEFAULT 'active'::text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT merchant_rate_limits_pkey PRIMARY KEY (id),
    CONSTRAINT merchant_rate_limits_merchant_id_endpoint_pattern_unique UNIQUE (merchant_id, endpoint_pattern)
);

CREATE TABLE IF NOT EXISTS public.merchant_usage_stats
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    merchant_id uuid NOT NULL,
    date date NOT NULL,
    endpoint character varying(255) COLLATE pg_catalog."default" NOT NULL,
    request_count integer DEFAULT 0,
    success_count integer DEFAULT 0,
    error_count integer DEFAULT 0,
    total_amount numeric(15, 2) DEFAULT '0'::numeric,
    transaction_count integer DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT merchant_usage_stats_pkey PRIMARY KEY (id),
    CONSTRAINT merchant_usage_stats_merchant_id_date_endpoint_unique UNIQUE (merchant_id, date, endpoint)
);

CREATE TABLE IF NOT EXISTS public.merchant_webhooks
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    merchant_id uuid NOT NULL,
    webhook_url character varying(500) COLLATE pg_catalog."default" NOT NULL,
    webhook_secret character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" DEFAULT 'active'::text,
    events jsonb,
    retry_attempts integer DEFAULT 3,
    retry_delay integer DEFAULT 5000,
    timeout integer DEFAULT 30000,
    last_triggered_at timestamp with time zone,
    success_count integer DEFAULT 0,
    failure_count integer DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT merchant_webhooks_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.merchants
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    merchant_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    merchant_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    business_type character varying(100) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    address jsonb,
    status text COLLATE pg_catalog."default" DEFAULT 'active'::text,
    settings jsonb,
    api_credentials jsonb,
    balance numeric(15, 2) DEFAULT '0'::numeric,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    website_url character varying(500) COLLATE pg_catalog."default",
    callback_url character varying(500) COLLATE pg_catalog."default",
    logo_url character varying(500) COLLATE pg_catalog."default",
    business_details jsonb,
    kyc_verified boolean DEFAULT false,
    kyc_verified_at timestamp with time zone,
    daily_limit numeric(15, 2),
    monthly_limit numeric(15, 2),
    last_active_at timestamp with time zone,
    tenant_id uuid NOT NULL,
    CONSTRAINT merchants_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.outbox_events
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    aggregate_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    aggregate_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    event_type character varying(150) COLLATE pg_catalog."default" NOT NULL,
    event_version integer NOT NULL DEFAULT 1,
    idempotency_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    correlation_id uuid,
    payload jsonb NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::text,
    retry_count integer NOT NULL DEFAULT 0,
    max_retries integer NOT NULL DEFAULT 3,
    next_retry_at timestamp with time zone,
    last_error text COLLATE pg_catalog."default",
    locked_until timestamp with time zone,
    processed_at timestamp with time zone,
    dlq_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    processing_started_at timestamp with time zone,
    CONSTRAINT outbox_events_pkey PRIMARY KEY (id),
    CONSTRAINT uq_outbox_tenant_event_idempotency UNIQUE (tenant_id, event_type, idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.payment_orders
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    order_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    amount numeric(15, 2) NOT NULL,
    currency character varying(3) COLLATE pg_catalog."default" DEFAULT 'INR'::character varying,
    status text COLLATE pg_catalog."default" DEFAULT 'created'::text,
    customer_id character varying(100) COLLATE pg_catalog."default",
    customer_email character varying(255) COLLATE pg_catalog."default",
    customer_phone character varying(20) COLLATE pg_catalog."default",
    customer_details jsonb,
    billing_address jsonb,
    shipping_address jsonb,
    line_items jsonb,
    payment_method character varying(50) COLLATE pg_catalog."default",
    gateway character varying(50) COLLATE pg_catalog."default",
    gateway_order_id character varying(255) COLLATE pg_catalog."default",
    callback_url character varying(500) COLLATE pg_catalog."default",
    webhook_url character varying(500) COLLATE pg_catalog."default",
    metadata jsonb,
    expires_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_orders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payment_signals
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    signal_type text COLLATE pg_catalog."default" NOT NULL,
    severity text COLLATE pg_catalog."default" NOT NULL,
    signal_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'OPEN'::text,
    source_type text COLLATE pg_catalog."default" NOT NULL,
    source_id uuid,
    transaction_id uuid,
    transaction_ref character varying(100) COLLATE pg_catalog."default",
    gateway_name character varying(80) COLLATE pg_catalog."default",
    gateway_payment_id character varying(255) COLLATE pg_catalog."default",
    gateway_event_id character varying(255) COLLATE pg_catalog."default",
    impact_amount numeric(15, 2),
    currency character varying(3) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default" NOT NULL,
    suggested_action text COLLATE pg_catalog."default",
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_signals_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payment_state_transitions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    transaction_id uuid,
    transaction_ref character varying(100) COLLATE pg_catalog."default" NOT NULL,
    gateway_name character varying(80) COLLATE pg_catalog."default",
    gateway_payment_id character varying(255) COLLATE pg_catalog."default",
    previous_status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    new_status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    transition_reason character varying(150) COLLATE pg_catalog."default" NOT NULL,
    gateway_event_id character varying(255) COLLATE pg_catalog."default",
    webhook_event_id uuid,
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_state_transitions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payout_attempts
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    payout_instruction_id uuid NOT NULL,
    attempt_number integer NOT NULL,
    provider_name character varying(80) COLLATE pg_catalog."default" NOT NULL,
    bank_idempotency_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    request_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    response_payload jsonb,
    provider_payout_id character varying(255) COLLATE pg_catalog."default",
    provider_status character varying(80) COLLATE pg_catalog."default",
    attempt_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'CREATED'::text,
    failure_reason text COLLATE pg_catalog."default",
    submitted_at timestamp with time zone,
    completed_at timestamp with time zone,
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payout_attempts_pkey PRIMARY KEY (id),
    CONSTRAINT uq_payout_attempt_instruction_number UNIQUE (tenant_id, payout_instruction_id, attempt_number),
    CONSTRAINT uq_payout_attempt_provider_idempotency UNIQUE (tenant_id, provider_name, bank_idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.payout_instructions
(
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    settlement_id uuid,
    settlement_ref character varying(100) COLLATE pg_catalog."default",
    merchant_id uuid,
    beneficiary_id uuid,
    bank_account_id uuid,
    payout_amount numeric(15, 2) NOT NULL,
    currency character varying(3) COLLATE pg_catalog."default" NOT NULL DEFAULT 'INR'::character varying,
    payout_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'CREATED'::text,
    bank_idempotency_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    utr_number character varying(100) COLLATE pg_catalog."default",
    bank_reference_number character varying(100) COLLATE pg_catalog."default",
    bank_transaction_id character varying(100) COLLATE pg_catalog."default",
    submitted_at timestamp with time zone,
    accepted_at timestamp with time zone,
    completed_at timestamp with time zone,
    failed_at timestamp with time zone,
    returned_at timestamp with time zone,
    reversed_at timestamp with time zone,
    return_reason text COLLATE pg_catalog."default",
    failure_reason text COLLATE pg_catalog."default",
    retry_count integer NOT NULL DEFAULT 0,
    raw_bank_response jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    correlation_id uuid,
    settlement_batch_id uuid,
    reservation_id uuid,
    batch_ref character varying(120) COLLATE pg_catalog."default",
    provider_name character varying(80) COLLATE pg_catalog."default",
    provider_payout_id character varying(255) COLLATE pg_catalog."default",
    provider_status character varying(80) COLLATE pg_catalog."default",
    queued_at timestamp with time zone,
    processing_at timestamp with time zone,
    timeout_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    provider_status_reason text COLLATE pg_catalog."default",
    max_retries integer NOT NULL DEFAULT 3,
    raw_callback_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    outbox_event_id uuid,
    ledger_transaction_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT payout_instructions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_payout_instruction_tenant_idempotency UNIQUE (tenant_id, bank_idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.payout_provider_events
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    provider_name character varying(80) COLLATE pg_catalog."default" NOT NULL,
    provider_event_id character varying(255) COLLATE pg_catalog."default",
    provider_event_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    provider_payout_id character varying(255) COLLATE pg_catalog."default",
    bank_idempotency_key character varying(255) COLLATE pg_catalog."default",
    payout_instruction_id uuid,
    raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    raw_headers jsonb NOT NULL DEFAULT '{}'::jsonb,
    payload_hash character varying(128) COLLATE pg_catalog."default" NOT NULL,
    signature_header character varying(500) COLLATE pg_catalog."default",
    signature_verified boolean NOT NULL DEFAULT false,
    verification_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::text,
    event_created_at timestamp with time zone,
    received_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at timestamp with time zone,
    processing_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'RECEIVED'::text,
    failure_reason text COLLATE pg_catalog."default",
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payout_provider_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payout_signals
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    signal_type text COLLATE pg_catalog."default" NOT NULL,
    severity text COLLATE pg_catalog."default" NOT NULL,
    signal_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'OPEN'::text,
    source_type text COLLATE pg_catalog."default" NOT NULL,
    source_id uuid,
    payout_instruction_id uuid,
    payout_attempt_id uuid,
    provider_event_id uuid,
    settlement_batch_id uuid,
    reservation_id uuid,
    merchant_id uuid,
    impact_amount numeric(15, 2),
    currency character varying(3) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default" NOT NULL,
    suggested_action text COLLATE pg_catalog."default",
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payout_signals_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pci_compliance_log
(
    id serial NOT NULL,
    check_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    requirement character varying(20) COLLATE pg_catalog."default" NOT NULL,
    requirement_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    violations jsonb,
    controls jsonb,
    checked_by character varying(100) COLLATE pg_catalog."default",
    checked_at timestamp with time zone NOT NULL,
    next_review_date timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pci_compliance_log_pkey PRIMARY KEY (id),
    CONSTRAINT pci_compliance_log_check_id_unique UNIQUE (check_id)
);

CREATE TABLE IF NOT EXISTS public.platform_users
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" DEFAULT 'active'::text,
    last_login_at timestamp with time zone,
    created_by uuid,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT platform_users_pkey PRIMARY KEY (id),
    CONSTRAINT platform_users_email_unique UNIQUE (email),
    CONSTRAINT platform_users_username_unique UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.pricing_rules
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    merchant_id uuid,
    gateway_name character varying(80) COLLATE pg_catalog."default" NOT NULL,
    payment_method character varying(50) COLLATE pg_catalog."default",
    rule_type text COLLATE pg_catalog."default" NOT NULL,
    mdr_percentage numeric(10, 4),
    fixed_fee numeric(15, 2),
    gst_percentage numeric(10, 4),
    effective_from timestamp with time zone NOT NULL,
    effective_to timestamp with time zone,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'ACTIVE'::text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pricing_rules_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.reconciliation_bank_settlements
(
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    settlement_id uuid,
    settlement_ref character varying(100) COLLATE pg_catalog."default",
    payout_instruction_id uuid,
    bank_statement_line_id uuid,
    reconciliation_status text COLLATE pg_catalog."default" NOT NULL,
    settlement_amount numeric(15, 2),
    payout_amount numeric(15, 2),
    bank_amount numeric(15, 2),
    discrepancy_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    settlement_currency character varying(3) COLLATE pg_catalog."default",
    bank_currency character varying(3) COLLATE pg_catalog."default",
    expected_utr_number character varying(100) COLLATE pg_catalog."default",
    actual_utr_number character varying(100) COLLATE pg_catalog."default",
    expected_bank_reference_number character varying(100) COLLATE pg_catalog."default",
    actual_bank_reference_number character varying(100) COLLATE pg_catalog."default",
    expected_bank_transaction_id character varying(100) COLLATE pg_catalog."default",
    actual_bank_transaction_id character varying(100) COLLATE pg_catalog."default",
    expected_bank_date date,
    actual_bank_date date,
    checked_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reconciliation_bank_settlements_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.reconciliation_batches
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    batch_ref character varying(100) COLLATE pg_catalog."default" NOT NULL,
    reconciliation_type text COLLATE pg_catalog."default" NOT NULL,
    gateway_name character varying(50) COLLATE pg_catalog."default",
    gateway_settlement_id character varying(100) COLLATE pg_catalog."default",
    period_from date NOT NULL,
    period_to date NOT NULL,
    total_transactions integer DEFAULT 0,
    matched_transactions integer DEFAULT 0,
    missing_transactions integer DEFAULT 0,
    mismatched_transactions integer DEFAULT 0,
    duplicate_transactions integer DEFAULT 0,
    expected_amount numeric(15, 2),
    actual_amount numeric(15, 2),
    difference_amount numeric(15, 2),
    status text COLLATE pg_catalog."default" DEFAULT 'in_progress'::text,
    file_name character varying(255) COLLATE pg_catalog."default",
    file_path character varying(500) COLLATE pg_catalog."default",
    metadata jsonb,
    discrepancies jsonb,
    created_by character varying(100) COLLATE pg_catalog."default",
    resolved_by character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp with time zone,
    resolved_at timestamp with time zone,
    CONSTRAINT reconciliation_batches_pkey PRIMARY KEY (id),
    CONSTRAINT reconciliation_batches_batch_ref_unique UNIQUE (batch_ref)
);

CREATE TABLE IF NOT EXISTS public.reconciliation_exception_audit_events
(
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    case_id uuid NOT NULL,
    action_type text COLLATE pg_catalog."default" NOT NULL,
    previous_status character varying(50) COLLATE pg_catalog."default",
    new_status character varying(50) COLLATE pg_catalog."default",
    performed_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    performed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason text COLLATE pg_catalog."default",
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT reconciliation_exception_audit_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.reconciliation_exception_cases
(
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    source_type text COLLATE pg_catalog."default" NOT NULL,
    source_reconciliation_id uuid NOT NULL,
    source_status character varying(100) COLLATE pg_catalog."default" NOT NULL,
    case_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'OPEN'::text,
    severity text COLLATE pg_catalog."default" NOT NULL DEFAULT 'MEDIUM'::text,
    priority text COLLATE pg_catalog."default" NOT NULL DEFAULT 'NORMAL'::text,
    assigned_to character varying(100) COLLATE pg_catalog."default",
    assigned_by character varying(100) COLLATE pg_catalog."default",
    assigned_at timestamp with time zone,
    opened_by character varying(100) COLLATE pg_catalog."default",
    opened_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_by character varying(100) COLLATE pg_catalog."default",
    resolved_at timestamp with time zone,
    resolution_type text COLLATE pg_catalog."default",
    resolution_reason text COLLATE pg_catalog."default",
    resolution_notes text COLLATE pg_catalog."default",
    approval_required boolean NOT NULL DEFAULT false,
    approval_request_id uuid,
    last_action_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reconciliation_exception_cases_pkey PRIMARY KEY (id),
    CONSTRAINT uq_recon_exception_source UNIQUE (tenant_id, source_type, source_reconciliation_id)
);

CREATE TABLE IF NOT EXISTS public.reconciliation_exception_comments
(
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    case_id uuid NOT NULL,
    comment_text text COLLATE pg_catalog."default" NOT NULL,
    comment_type text COLLATE pg_catalog."default" NOT NULL DEFAULT 'NOTE'::text,
    created_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT reconciliation_exception_comments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.reconciliation_items
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    batch_id uuid NOT NULL,
    transaction_id uuid,
    ledger_transaction_id uuid,
    external_ref character varying(100) COLLATE pg_catalog."default",
    external_transaction_id character varying(100) COLLATE pg_catalog."default",
    match_status text COLLATE pg_catalog."default" NOT NULL,
    internal_amount numeric(15, 2),
    external_amount numeric(15, 2),
    difference_amount numeric(15, 2),
    resolution_status text COLLATE pg_catalog."default" DEFAULT 'unresolved'::text,
    resolution_notes text COLLATE pg_catalog."default",
    resolved_by character varying(100) COLLATE pg_catalog."default",
    resolved_at timestamp with time zone,
    metadata jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reconciliation_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.reconciliation_settlements
(
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    settlement_id uuid,
    settlement_ref character varying(100) COLLATE pg_catalog."default",
    ledger_transaction_id uuid,
    reconciliation_status text COLLATE pg_catalog."default" NOT NULL,
    settlement_gross_amount numeric(15, 2),
    ledger_gross_amount numeric(15, 2),
    settlement_fee_amount numeric(15, 2),
    ledger_fee_amount numeric(15, 2),
    settlement_net_amount numeric(15, 2),
    ledger_net_amount numeric(15, 2),
    discrepancy_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    currency character varying(3) COLLATE pg_catalog."default",
    checked_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    correlation_id uuid,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reconciliation_settlements_pkey PRIMARY KEY (id),
    CONSTRAINT uq_reconciliation_settlements_tenant_ref UNIQUE (tenant_id, settlement_ref)
);

CREATE TABLE IF NOT EXISTS public.reconciliation_transactions
(
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    transaction_id uuid NOT NULL,
    transaction_ref character varying(100) COLLATE pg_catalog."default" NOT NULL,
    ledger_transaction_id uuid,
    reconciliation_status text COLLATE pg_catalog."default" NOT NULL,
    transaction_amount numeric(15, 2) NOT NULL,
    ledger_amount numeric(15, 2),
    currency character varying(3) COLLATE pg_catalog."default" NOT NULL,
    discrepancy_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    checked_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    correlation_id uuid,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reconciliation_transactions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_reconciliation_transactions_tenant_ref UNIQUE (tenant_id, transaction_ref)
);

CREATE TABLE IF NOT EXISTS public.refunds
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    merchant_id uuid NOT NULL,
    transaction_id uuid NOT NULL,
    refund_ref character varying(100) COLLATE pg_catalog."default" NOT NULL,
    refund_amount numeric(15, 2) NOT NULL,
    original_amount numeric(15, 2) NOT NULL,
    currency character varying(3) COLLATE pg_catalog."default" DEFAULT 'INR'::character varying,
    refund_type text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'initiated'::text,
    reason character varying(500) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    gateway_refund_id character varying(255) COLLATE pg_catalog."default",
    gateway_response_code character varying(50) COLLATE pg_catalog."default",
    gateway_response_message text COLLATE pg_catalog."default",
    metadata jsonb,
    initiated_by character varying(255) COLLATE pg_catalog."default",
    initiated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT refunds_pkey PRIMARY KEY (id),
    CONSTRAINT refunds_refund_ref_unique UNIQUE (refund_ref)
);

CREATE TABLE IF NOT EXISTS public.security_alerts
(
    id serial NOT NULL,
    alert_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    alert_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    severity character varying(20) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    affected_user character varying(100) COLLATE pg_catalog."default",
    affected_resource character varying(255) COLLATE pg_catalog."default",
    ip_address character varying(45) COLLATE pg_catalog."default",
    details jsonb,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'OPEN'::character varying,
    resolution_notes text COLLATE pg_catalog."default",
    resolved_by character varying(100) COLLATE pg_catalog."default",
    resolved_at timestamp with time zone,
    triggered_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT security_alerts_pkey PRIMARY KEY (id),
    CONSTRAINT security_alerts_alert_id_unique UNIQUE (alert_id)
);

CREATE TABLE IF NOT EXISTS public.sensitive_data_access
(
    id serial NOT NULL,
    access_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    user_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    user_role character varying(50) COLLATE pg_catalog."default",
    data_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    data_id character varying(100) COLLATE pg_catalog."default",
    access_method character varying(50) COLLATE pg_catalog."default",
    justification character varying(500) COLLATE pg_catalog."default",
    approved_by character varying(100) COLLATE pg_catalog."default",
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    authorized boolean DEFAULT true,
    denial_reason text COLLATE pg_catalog."default",
    accessed_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT sensitive_data_access_pkey PRIMARY KEY (id),
    CONSTRAINT sensitive_data_access_access_id_unique UNIQUE (access_id)
);

CREATE TABLE IF NOT EXISTS public.settlement_batches
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    batch_ref character varying(120) COLLATE pg_catalog."default" NOT NULL,
    merchant_id uuid,
    beneficiary_id uuid,
    bank_account_id uuid,
    settlement_cycle_start timestamp with time zone,
    settlement_cycle_end timestamp with time zone,
    scheduled_settlement_date date,
    batch_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'DRAFT'::text,
    gross_payable_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    total_fee_deduction numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    total_tax_deduction numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    total_adjustment_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    net_settlement_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    reserved_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    currency character varying(3) COLLATE pg_catalog."default" NOT NULL DEFAULT 'INR'::character varying,
    item_count integer NOT NULL DEFAULT 0,
    eligible_item_count integer NOT NULL DEFAULT 0,
    ineligible_item_count integer NOT NULL DEFAULT 0,
    reservation_expires_at timestamp with time zone,
    reserved_at timestamp with time zone,
    reserved_by character varying(100) COLLATE pg_catalog."default",
    cancelled_at timestamp with time zone,
    cancelled_by character varying(100) COLLATE pg_catalog."default",
    cancellation_reason text COLLATE pg_catalog."default",
    payout_instruction_id uuid,
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT settlement_batches_pkey PRIMARY KEY (id),
    CONSTRAINT uq_settlement_batches_tenant_ref UNIQUE (tenant_id, batch_ref)
);

CREATE TABLE IF NOT EXISTS public.settlement_fund_reservations
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    reservation_ref character varying(120) COLLATE pg_catalog."default" NOT NULL,
    batch_id uuid NOT NULL,
    merchant_id uuid,
    currency character varying(3) COLLATE pg_catalog."default" NOT NULL DEFAULT 'INR'::character varying,
    reservation_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'ACTIVE'::text,
    reserved_amount numeric(15, 2) NOT NULL,
    available_escrow_amount numeric(15, 2),
    available_merchant_payable_amount numeric(15, 2),
    reserved_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp with time zone,
    released_at timestamp with time zone,
    consumed_at timestamp with time zone,
    failure_reason text COLLATE pg_catalog."default",
    idempotency_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT settlement_fund_reservations_pkey PRIMARY KEY (id),
    CONSTRAINT uq_settlement_reservations_tenant_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT uq_settlement_reservations_tenant_ref UNIQUE (tenant_id, reservation_ref)
);

CREATE TABLE IF NOT EXISTS public.settlement_items
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    batch_id uuid NOT NULL,
    transaction_id uuid,
    transaction_ref character varying(100) COLLATE pg_catalog."default" NOT NULL,
    merchant_id uuid,
    ledger_transaction_id uuid,
    gateway_settlement_line_id uuid,
    item_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'CANDIDATE'::text,
    eligibility_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::text,
    eligibility_reason text COLLATE pg_catalog."default",
    eligibility_details jsonb NOT NULL DEFAULT '{}'::jsonb,
    gross_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    fee_deduction numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    tax_deduction numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    adjustment_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    net_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    currency character varying(3) COLLATE pg_catalog."default" NOT NULL DEFAULT 'INR'::character varying,
    reserved_amount numeric(15, 2) NOT NULL DEFAULT '0'::numeric,
    reserved_at timestamp with time zone,
    released_at timestamp with time zone,
    release_reason text COLLATE pg_catalog."default",
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT settlement_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.settlement_signals
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    signal_type text COLLATE pg_catalog."default" NOT NULL,
    severity text COLLATE pg_catalog."default" NOT NULL,
    signal_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'OPEN'::text,
    source_type text COLLATE pg_catalog."default" NOT NULL,
    source_id uuid,
    batch_id uuid,
    item_id uuid,
    reservation_id uuid,
    merchant_id uuid,
    transaction_ref character varying(100) COLLATE pg_catalog."default",
    impact_amount numeric(15, 2),
    currency character varying(3) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default" NOT NULL,
    suggested_action text COLLATE pg_catalog."default",
    correlation_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT settlement_signals_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.settlements
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    merchant_id uuid NOT NULL,
    settlement_ref character varying(100) COLLATE pg_catalog."default" NOT NULL,
    settlement_date date NOT NULL,
    period_from date NOT NULL,
    period_to date NOT NULL,
    gross_amount numeric(15, 2) NOT NULL,
    fees_amount numeric(15, 2) NOT NULL,
    net_amount numeric(15, 2) NOT NULL,
    bank_account_number character varying(50) COLLATE pg_catalog."default",
    bank_ifsc character varying(20) COLLATE pg_catalog."default",
    bank_name character varying(100) COLLATE pg_catalog."default",
    utr_number character varying(50) COLLATE pg_catalog."default",
    ledger_transaction_id uuid,
    metadata jsonb,
    created_by character varying(100) COLLATE pg_catalog."default",
    approved_by character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    approved_at timestamp with time zone,
    completed_at timestamp with time zone,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'CREATED'::text,
    funds_reserved_at timestamp with time zone,
    sent_to_bank_at timestamp with time zone,
    bank_confirmed_at timestamp with time zone,
    settled_at timestamp with time zone,
    failed_at timestamp with time zone,
    bank_reference_number character varying(100) COLLATE pg_catalog."default",
    bank_transaction_id character varying(100) COLLATE pg_catalog."default",
    settlement_batch_id character varying(100) COLLATE pg_catalog."default",
    retry_count integer DEFAULT 0,
    max_retries integer DEFAULT 3,
    next_retry_at timestamp with time zone,
    last_retry_at timestamp with time zone,
    failure_reason text COLLATE pg_catalog."default",
    retry_history jsonb,
    state_transitions jsonb,
    CONSTRAINT settlements_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.system_config
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    config_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    config_value jsonb NOT NULL,
    category character varying(100) COLLATE pg_catalog."default" NOT NULL,
    is_financial boolean DEFAULT false,
    version integer DEFAULT 1,
    description text COLLATE pg_catalog."default",
    updated_by uuid,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT system_config_pkey PRIMARY KEY (id),
    CONSTRAINT system_config_config_key_unique UNIQUE (config_key)
);

CREATE TABLE IF NOT EXISTS public.tenants
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_code character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tenant_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tenants_pkey PRIMARY KEY (id),
    CONSTRAINT tenants_tenant_code_unique UNIQUE (tenant_code)
);

CREATE TABLE IF NOT EXISTS public.token_vault
(
    id serial NOT NULL,
    vault_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    token_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    encrypted_data text COLLATE pg_catalog."default" NOT NULL,
    iv character varying(32) COLLATE pg_catalog."default" NOT NULL,
    auth_tag character varying(32) COLLATE pg_catalog."default" NOT NULL,
    last_4 character varying(10) COLLATE pg_catalog."default",
    first_6 character varying(10) COLLATE pg_catalog."default",
    masked_value character varying(255) COLLATE pg_catalog."default",
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_accessed_at timestamp with time zone,
    access_count integer DEFAULT 0,
    revoked boolean DEFAULT false,
    CONSTRAINT token_vault_pkey PRIMARY KEY (id),
    CONSTRAINT token_vault_token_unique UNIQUE (token),
    CONSTRAINT token_vault_vault_id_unique UNIQUE (vault_id)
);

CREATE TABLE IF NOT EXISTS public.transactions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    order_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    transaction_ref character varying(100) COLLATE pg_catalog."default",
    payment_method character varying(50) COLLATE pg_catalog."default" NOT NULL,
    gateway character varying(50) COLLATE pg_catalog."default" NOT NULL,
    amount numeric(15, 2) NOT NULL,
    currency character varying(3) COLLATE pg_catalog."default" DEFAULT 'INR'::character varying,
    status text COLLATE pg_catalog."default" DEFAULT 'pending'::text,
    customer_email character varying(255) COLLATE pg_catalog."default",
    customer_phone character varying(20) COLLATE pg_catalog."default",
    customer_name character varying(255) COLLATE pg_catalog."default",
    metadata jsonb,
    gateway_transaction_id character varying(255) COLLATE pg_catalog."default",
    gateway_response_code character varying(50) COLLATE pg_catalog."default",
    gateway_response_message text COLLATE pg_catalog."default",
    initiated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT transactions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.webhook_delivery_logs
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    webhook_id uuid NOT NULL,
    merchant_id uuid NOT NULL,
    event_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    payload jsonb,
    status text COLLATE pg_catalog."default" DEFAULT 'pending'::text,
    attempt_count integer DEFAULT 0,
    response_code integer,
    response_body text COLLATE pg_catalog."default",
    error_message text COLLATE pg_catalog."default",
    next_retry_at timestamp with time zone,
    delivered_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT webhook_delivery_logs_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.approval_requests
    ADD CONSTRAINT approval_requests_approver_id_foreign FOREIGN KEY (approver_id)
    REFERENCES public.platform_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS approval_requests_approver_id_index
    ON public.approval_requests(approver_id);


ALTER TABLE IF EXISTS public.approval_requests
    ADD CONSTRAINT approval_requests_requestor_id_foreign FOREIGN KEY (requestor_id)
    REFERENCES public.platform_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS approval_requests_requestor_id_index
    ON public.approval_requests(requestor_id);


ALTER TABLE IF EXISTS public.audit_portal_access_log
    ADD CONSTRAINT audit_portal_access_log_auditor_user_id_foreign FOREIGN KEY (auditor_user_id)
    REFERENCES public.platform_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS audit_portal_access_log_auditor_user_id_index
    ON public.audit_portal_access_log(auditor_user_id);


ALTER TABLE IF EXISTS public.auditor_access_windows
    ADD CONSTRAINT auditor_access_windows_auditor_user_id_foreign FOREIGN KEY (auditor_user_id)
    REFERENCES public.platform_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS auditor_access_windows_auditor_user_id_index
    ON public.auditor_access_windows(auditor_user_id);


ALTER TABLE IF EXISTS public.bank_statement_lines
    ADD CONSTRAINT bank_statement_lines_batch_id_foreign FOREIGN KEY (batch_id)
    REFERENCES public.bank_statement_batches (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS bank_statement_lines_batch_id_index
    ON public.bank_statement_lines(batch_id);


ALTER TABLE IF EXISTS public.config_history
    ADD CONSTRAINT config_history_changed_by_foreign FOREIGN KEY (changed_by)
    REFERENCES public.platform_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS config_history_changed_by_index
    ON public.config_history(changed_by);


ALTER TABLE IF EXISTS public.config_history
    ADD CONSTRAINT config_history_config_id_foreign FOREIGN KEY (config_id)
    REFERENCES public.system_config (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS config_history_config_id_index
    ON public.config_history(config_id);


ALTER TABLE IF EXISTS public.disputes
    ADD CONSTRAINT disputes_transaction_id_foreign FOREIGN KEY (transaction_id)
    REFERENCES public.transactions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS disputes_transaction_id_index
    ON public.disputes(transaction_id);


ALTER TABLE IF EXISTS public.gateway_settlement_lines
    ADD CONSTRAINT fk_gateway_setl_lines_pricing_rule FOREIGN KEY (pricing_rule_id)
    REFERENCES public.pricing_rules (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.gateway_settlement_lines
    ADD CONSTRAINT gateway_settlement_lines_batch_id_foreign FOREIGN KEY (batch_id)
    REFERENCES public.gateway_settlement_batches (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS gateway_settlement_lines_batch_id_index
    ON public.gateway_settlement_lines(batch_id);


ALTER TABLE IF EXISTS public.gateway_settlement_lines
    ADD CONSTRAINT gateway_settlement_lines_ledger_transaction_id_foreign FOREIGN KEY (ledger_transaction_id)
    REFERENCES public.ledger_transactions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS gateway_settlement_lines_ledger_transaction_id_index
    ON public.gateway_settlement_lines(ledger_transaction_id);


ALTER TABLE IF EXISTS public.gateway_settlement_lines
    ADD CONSTRAINT gateway_settlement_lines_outbox_event_id_foreign FOREIGN KEY (outbox_event_id)
    REFERENCES public.outbox_events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS gateway_settlement_lines_outbox_event_id_index
    ON public.gateway_settlement_lines(outbox_event_id);


ALTER TABLE IF EXISTS public.gateway_settlement_lines
    ADD CONSTRAINT gateway_settlement_lines_transaction_id_foreign FOREIGN KEY (transaction_id)
    REFERENCES public.transactions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS gateway_settlement_lines_transaction_id_index
    ON public.gateway_settlement_lines(transaction_id);


ALTER TABLE IF EXISTS public.gateway_settlement_signals
    ADD CONSTRAINT gateway_settlement_signals_batch_id_foreign FOREIGN KEY (batch_id)
    REFERENCES public.gateway_settlement_batches (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS gateway_settlement_signals_batch_id_index
    ON public.gateway_settlement_signals(batch_id);


ALTER TABLE IF EXISTS public.gateway_settlement_signals
    ADD CONSTRAINT gateway_settlement_signals_line_id_foreign FOREIGN KEY (line_id)
    REFERENCES public.gateway_settlement_lines (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS gateway_settlement_signals_line_id_index
    ON public.gateway_settlement_signals(line_id);


ALTER TABLE IF EXISTS public.ledger_entries
    ADD CONSTRAINT ledger_entries_account_id_foreign FOREIGN KEY (account_id)
    REFERENCES public.ledger_accounts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.ledger_entries
    ADD CONSTRAINT ledger_entries_transaction_id_foreign FOREIGN KEY (transaction_id)
    REFERENCES public.ledger_transactions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.ledger_locks
    ADD CONSTRAINT ledger_locks_accounting_period_id_foreign FOREIGN KEY (accounting_period_id)
    REFERENCES public.accounting_periods (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.merchant_api_keys
    ADD CONSTRAINT merchant_api_keys_merchant_id_foreign FOREIGN KEY (merchant_id)
    REFERENCES public.merchants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS merchant_api_keys_merchant_id_index
    ON public.merchant_api_keys(merchant_id);


ALTER TABLE IF EXISTS public.merchant_ip_whitelist
    ADD CONSTRAINT merchant_ip_whitelist_merchant_id_foreign FOREIGN KEY (merchant_id)
    REFERENCES public.merchants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS merchant_ip_whitelist_merchant_id_index
    ON public.merchant_ip_whitelist(merchant_id);


ALTER TABLE IF EXISTS public.merchant_rate_limits
    ADD CONSTRAINT merchant_rate_limits_merchant_id_foreign FOREIGN KEY (merchant_id)
    REFERENCES public.merchants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS merchant_rate_limits_merchant_id_index
    ON public.merchant_rate_limits(merchant_id);


ALTER TABLE IF EXISTS public.merchant_usage_stats
    ADD CONSTRAINT merchant_usage_stats_merchant_id_foreign FOREIGN KEY (merchant_id)
    REFERENCES public.merchants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS merchant_usage_stats_merchant_id_index
    ON public.merchant_usage_stats(merchant_id);


ALTER TABLE IF EXISTS public.merchant_webhooks
    ADD CONSTRAINT merchant_webhooks_merchant_id_foreign FOREIGN KEY (merchant_id)
    REFERENCES public.merchants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS merchant_webhooks_merchant_id_index
    ON public.merchant_webhooks(merchant_id);


ALTER TABLE IF EXISTS public.payout_attempts
    ADD CONSTRAINT payout_attempts_payout_instruction_id_foreign FOREIGN KEY (payout_instruction_id)
    REFERENCES public.payout_instructions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS payout_attempts_payout_instruction_id_index
    ON public.payout_attempts(payout_instruction_id);


ALTER TABLE IF EXISTS public.payout_instructions
    ADD CONSTRAINT fk_payout_instruction_ledger_transaction FOREIGN KEY (ledger_transaction_id)
    REFERENCES public.ledger_transactions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS payout_instructions_ledger_transaction_id_index
    ON public.payout_instructions(ledger_transaction_id);


ALTER TABLE IF EXISTS public.payout_instructions
    ADD CONSTRAINT fk_payout_instruction_outbox_event FOREIGN KEY (outbox_event_id)
    REFERENCES public.outbox_events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS payout_instructions_outbox_event_id_index
    ON public.payout_instructions(outbox_event_id);


ALTER TABLE IF EXISTS public.payout_instructions
    ADD CONSTRAINT fk_payout_instruction_reservation FOREIGN KEY (reservation_id)
    REFERENCES public.settlement_fund_reservations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS payout_instructions_reservation_id_index
    ON public.payout_instructions(reservation_id);


ALTER TABLE IF EXISTS public.payout_instructions
    ADD CONSTRAINT fk_payout_instruction_settlement_batch FOREIGN KEY (settlement_batch_id)
    REFERENCES public.settlement_batches (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS payout_instructions_settlement_batch_id_index
    ON public.payout_instructions(settlement_batch_id);


ALTER TABLE IF EXISTS public.payout_provider_events
    ADD CONSTRAINT payout_provider_events_payout_instruction_id_foreign FOREIGN KEY (payout_instruction_id)
    REFERENCES public.payout_instructions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS payout_provider_events_payout_instruction_id_index
    ON public.payout_provider_events(payout_instruction_id);


ALTER TABLE IF EXISTS public.payout_signals
    ADD CONSTRAINT payout_signals_payout_attempt_id_foreign FOREIGN KEY (payout_attempt_id)
    REFERENCES public.payout_attempts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS payout_signals_payout_attempt_id_index
    ON public.payout_signals(payout_attempt_id);


ALTER TABLE IF EXISTS public.payout_signals
    ADD CONSTRAINT payout_signals_payout_instruction_id_foreign FOREIGN KEY (payout_instruction_id)
    REFERENCES public.payout_instructions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS payout_signals_payout_instruction_id_index
    ON public.payout_signals(payout_instruction_id);


ALTER TABLE IF EXISTS public.payout_signals
    ADD CONSTRAINT payout_signals_provider_event_id_foreign FOREIGN KEY (provider_event_id)
    REFERENCES public.payout_provider_events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS payout_signals_provider_event_id_index
    ON public.payout_signals(provider_event_id);


ALTER TABLE IF EXISTS public.payout_signals
    ADD CONSTRAINT payout_signals_reservation_id_foreign FOREIGN KEY (reservation_id)
    REFERENCES public.settlement_fund_reservations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS payout_signals_reservation_id_index
    ON public.payout_signals(reservation_id);


ALTER TABLE IF EXISTS public.payout_signals
    ADD CONSTRAINT payout_signals_settlement_batch_id_foreign FOREIGN KEY (settlement_batch_id)
    REFERENCES public.settlement_batches (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS payout_signals_settlement_batch_id_index
    ON public.payout_signals(settlement_batch_id);


ALTER TABLE IF EXISTS public.platform_users
    ADD CONSTRAINT platform_users_created_by_foreign FOREIGN KEY (created_by)
    REFERENCES public.platform_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.reconciliation_bank_settlements
    ADD CONSTRAINT fk_recon_bank_setl_bank_statement_line FOREIGN KEY (bank_statement_line_id)
    REFERENCES public.bank_statement_lines (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS reconciliation_bank_settlements_bank_statement_line_id_index
    ON public.reconciliation_bank_settlements(bank_statement_line_id);


ALTER TABLE IF EXISTS public.reconciliation_bank_settlements
    ADD CONSTRAINT fk_recon_bank_setl_payout_instruction FOREIGN KEY (payout_instruction_id)
    REFERENCES public.payout_instructions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS reconciliation_bank_settlements_payout_instruction_id_index
    ON public.reconciliation_bank_settlements(payout_instruction_id);


ALTER TABLE IF EXISTS public.reconciliation_bank_settlements
    ADD CONSTRAINT fk_recon_bank_setl_settlement FOREIGN KEY (settlement_id)
    REFERENCES public.settlements (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS reconciliation_bank_settlements_settlement_id_index
    ON public.reconciliation_bank_settlements(settlement_id);


ALTER TABLE IF EXISTS public.reconciliation_exception_audit_events
    ADD CONSTRAINT reconciliation_exception_audit_events_case_id_foreign FOREIGN KEY (case_id)
    REFERENCES public.reconciliation_exception_cases (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS reconciliation_exception_audit_events_case_id_index
    ON public.reconciliation_exception_audit_events(case_id);


ALTER TABLE IF EXISTS public.reconciliation_exception_comments
    ADD CONSTRAINT reconciliation_exception_comments_case_id_foreign FOREIGN KEY (case_id)
    REFERENCES public.reconciliation_exception_cases (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS reconciliation_exception_comments_case_id_index
    ON public.reconciliation_exception_comments(case_id);


ALTER TABLE IF EXISTS public.reconciliation_items
    ADD CONSTRAINT reconciliation_items_batch_id_foreign FOREIGN KEY (batch_id)
    REFERENCES public.reconciliation_batches (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.refunds
    ADD CONSTRAINT refunds_transaction_id_foreign FOREIGN KEY (transaction_id)
    REFERENCES public.transactions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS refunds_transaction_id_index
    ON public.refunds(transaction_id);


ALTER TABLE IF EXISTS public.settlement_batches
    ADD CONSTRAINT settlement_batches_beneficiary_id_foreign FOREIGN KEY (beneficiary_id)
    REFERENCES public.beneficiaries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS settlement_batches_beneficiary_id_index
    ON public.settlement_batches(beneficiary_id);


ALTER TABLE IF EXISTS public.settlement_batches
    ADD CONSTRAINT settlement_batches_merchant_id_foreign FOREIGN KEY (merchant_id)
    REFERENCES public.merchants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS settlement_batches_merchant_id_index
    ON public.settlement_batches(merchant_id);


ALTER TABLE IF EXISTS public.settlement_batches
    ADD CONSTRAINT settlement_batches_payout_instruction_id_foreign FOREIGN KEY (payout_instruction_id)
    REFERENCES public.payout_instructions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS settlement_batches_payout_instruction_id_index
    ON public.settlement_batches(payout_instruction_id);


ALTER TABLE IF EXISTS public.settlement_fund_reservations
    ADD CONSTRAINT settlement_fund_reservations_batch_id_foreign FOREIGN KEY (batch_id)
    REFERENCES public.settlement_batches (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS settlement_fund_reservations_batch_id_index
    ON public.settlement_fund_reservations(batch_id);


ALTER TABLE IF EXISTS public.settlement_items
    ADD CONSTRAINT settlement_items_batch_id_foreign FOREIGN KEY (batch_id)
    REFERENCES public.settlement_batches (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS settlement_items_batch_id_index
    ON public.settlement_items(batch_id);


ALTER TABLE IF EXISTS public.settlement_items
    ADD CONSTRAINT settlement_items_gateway_settlement_line_id_foreign FOREIGN KEY (gateway_settlement_line_id)
    REFERENCES public.gateway_settlement_lines (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS settlement_items_gateway_settlement_line_id_index
    ON public.settlement_items(gateway_settlement_line_id);


ALTER TABLE IF EXISTS public.settlement_items
    ADD CONSTRAINT settlement_items_ledger_transaction_id_foreign FOREIGN KEY (ledger_transaction_id)
    REFERENCES public.ledger_transactions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS settlement_items_ledger_transaction_id_index
    ON public.settlement_items(ledger_transaction_id);


ALTER TABLE IF EXISTS public.settlement_items
    ADD CONSTRAINT settlement_items_transaction_id_foreign FOREIGN KEY (transaction_id)
    REFERENCES public.transactions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS settlement_items_transaction_id_index
    ON public.settlement_items(transaction_id);


ALTER TABLE IF EXISTS public.settlement_signals
    ADD CONSTRAINT settlement_signals_batch_id_foreign FOREIGN KEY (batch_id)
    REFERENCES public.settlement_batches (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS settlement_signals_batch_id_index
    ON public.settlement_signals(batch_id);


ALTER TABLE IF EXISTS public.settlement_signals
    ADD CONSTRAINT settlement_signals_item_id_foreign FOREIGN KEY (item_id)
    REFERENCES public.settlement_items (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS settlement_signals_item_id_index
    ON public.settlement_signals(item_id);


ALTER TABLE IF EXISTS public.settlement_signals
    ADD CONSTRAINT settlement_signals_reservation_id_foreign FOREIGN KEY (reservation_id)
    REFERENCES public.settlement_fund_reservations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS settlement_signals_reservation_id_index
    ON public.settlement_signals(reservation_id);


ALTER TABLE IF EXISTS public.settlements
    ADD CONSTRAINT settlements_ledger_transaction_id_foreign FOREIGN KEY (ledger_transaction_id)
    REFERENCES public.ledger_transactions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.system_config
    ADD CONSTRAINT system_config_updated_by_foreign FOREIGN KEY (updated_by)
    REFERENCES public.platform_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.webhook_delivery_logs
    ADD CONSTRAINT webhook_delivery_logs_merchant_id_foreign FOREIGN KEY (merchant_id)
    REFERENCES public.merchants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS webhook_delivery_logs_merchant_id_index
    ON public.webhook_delivery_logs(merchant_id);


ALTER TABLE IF EXISTS public.webhook_delivery_logs
    ADD CONSTRAINT webhook_delivery_logs_webhook_id_foreign FOREIGN KEY (webhook_id)
    REFERENCES public.merchant_webhooks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS webhook_delivery_logs_webhook_id_index
    ON public.webhook_delivery_logs(webhook_id);

END;